name: Docs Only Build

on:
  workflow_dispatch:

jobs:
  generate-docs:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Setup DocFX
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install docfx

      - name: Create Docs dir
        run: mkdir docs

      - name: Pwd
        run: pwd
        
      - name: Ls
        run: ls

      - name: DocFX Build
        run: docfx ./docfx_project/docfx.json -o docs
        continue-on-error: false

      - name: Ls
        run: ls docs

      - name: Ls
          run: ls docs/api

      - name: Copy
        run: cp -R docs/_site/* docs

      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
          force_orphan: true
